### ISSUE TITLE
open jot fail:  invalid key split

### ISSUE THREAD

**Issue by try-to-fly** [letieu/jot.lua#2]
Neovim Vesion: v0.9.4

E5108: Error executing lua: ...s/smile/.local/share/nvim/lazy/jot.lua/lua/jot/utils.lua:10: invalid key: split  
stack traceback:  
\[C\]: in function 'nvim\_open\_win'  
...s/smile/.local/share/nvim/lazy/jot.lua/lua/jot/utils.lua:10: in function 'view\_file'  
...rs/smile/.local/share/nvim/lazy/jot.lua/lua/jot/init.lua:21: in function 'open'  
/Users/smile/.config/nvim/lua/plugins/test.lua:6: in function \</Users/smile/.config/nvim/lua/plugins/test.lua:5>

**Comment by thohnb** [comment]
We are on same boat.  I get split error too
```
E5108: Error executing lua: .../thohnb/.local/share/nvim/lazy/jot.lua/lua/jot/utils.lua:10: invalid key: split
stack traceback:
        [C]: in function 'nvim_open_win'
        .../thohnb/.local/share/nvim/lazy/jot.lua/lua/jot/utils.lua:10: in function 'view_file'
        ...e/thohnb/.local/share/nvim/lazy/jot.lua/lua/jot/init.lua:21: in function 'open'
        /home/thohnb/.config/nvim/lua/core/keymaps.lua:26: in function </home/thohnb/.config/nvim/lua/core/keymaps.lua:26>
```

**Comment by letieu** [comment]
I fixed this issue
