### ISSUE TITLE
[BUG] Mini.starter + jot lua = screen not resize .

### ISSUE THREAD

**Issue by thohnb** [letieu/jot.lua#4]
Hello @letieu.
I'm currently using **mini.starter**  and **jot.lua** . But somehow , when open the jot. It make mini.starter look like this. 
 Maybe we need floating mode?
![ảnh](https://github.com/letieu/jot.lua/assets/125535323/725b1201-5b38-43d0-89cd-ddc33138c710)

- **jot.lua**

```lua
{
        "letieu/jot.lua",
        dependencies = { "nvim-lua/plenary.nvim" },
        config = function()
          require("jot").setup({
            win_opts = {
              split = "left",
              focusable = false,
            },
           -- Set keybind
           vim.keymap.set("n", "<leader>j", function() require("jot").toggle() end, { noremap = true, silent = true })
         })
         end
      }
```

- **mini.starter**
```lua
return {
    "echasnovski/mini.starter",
    version = false, -- wait till new 0.7.0 release to put it back on semver
    config = function()
        local header_art = 
        [[
         Hello World!
        ]]

        local starter = require('mini.starter')
        starter.setup({
          evaluate_single = true,
          query_updaters = '',
          items = {
            starter.sections.telescope(),
          },
          content_hooks = {
            starter.gen_hook.adding_bullet("- "),
            starter.gen_hook.aligning('center', 'center'),
          },
          header = header_art,
          footer = '',
          
        })
        vim.cmd([[
                    augroup MiniStarterKeymaps
                      au!
                      au User MiniStarterOpened nmap <buffer> s <Cmd>lua MiniStarter.update_current_item('next')<CR>
                      au User MiniStarterOpened nmap <buffer> w <Cmd>lua MiniStarter.update_current_item('prev')<CR>
                    augroup END
                  ]])
        vim.api.nvim_set_keymap('n', '@', ':lua MiniStarter.open()<CR>', { noremap = true, silent = true })

    end,
  }
```

**Comment by letieu** [comment]
<img width="879" alt="Screenshot 2024-04-03 at 8 04 22 PM" src="https://github.com/letieu/jot.lua/assets/53562817/74d0e182-025f-4e5e-9e62-72d78186b2d3">

@thohnb 

I think this due to behaviour of mini.starter, It can't resize window when have  another open beside.

You can try open a split window by `:vsplit` and it still look like above, not only jot.lua

**Comment by letieu** [comment]
@thohnb 

In case you want to open flot float only when on mini.starter, you can try pass `win_opt` when call `toggle` function

```lua
require('jot').toggle({
  relative = "editor",
  width = 100,
  height = 30,
  row = 5,
  col = 35,
})```

**Comment by thohnb** [comment]
@letieu Oh i see. Look like in my side. 
Thanks . I figured out how to fix my problem now.. 
For anyone who having same problem like me or for future research. 
You can use `MiniStarter.refresh()`. 
Luckily the **jot** plugins is easy to config 
![ảnh](https://github.com/letieu/jot.lua/assets/125535323/5d65e8b5-3566-46a0-8031-65c4d582d0b4)
